---
title: "Shiny Application and Reproducible"
author: "Yeoh Eik Den"
date: "2/4/2017"
output: ioslides_presentation
---

## Instruction

First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

## Shiny Application
- Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user 
- will need to get started using your application.
- Deploy the application on Rstudio's shiny server
- Share the application link by pasting it into the provided text box
- Share your server.R and ui.R code on github
- The application must include the following:

Some form of input (widget: textbox, radio button, checkbox, ...)
Some operation on the ui input in sever.R. Some reactive output displayed as a result of server calculations


## Reproducible Pitch Presentation

Your presentation must satisfy the following

- It must be done in Slidify or Rstudio Presenter
- It must be 5 pages
- It must be hosted on github or Rpubs
- It must contained some embedded R code that gets run when slidifying the document

## URLs
Source code for ui.R and server.R files are available on the GitHub:https://github.com/eikden/eikden.github.io

Presentation Slide is available at: http://rpubs.com/eikden/shinyapplication

The app developed for the first part of the assignment is available at: https://eikden.shinyapps.io/MTCARS_Interaction_Demo/




